In [1]:
#pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.5 MB 14.8 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.5 MB 13.9 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.5 MB 15.3 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 15.2 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
a=np.array(9)
print(a)
print(type(a))
print(a.ndim)

9
<class 'numpy.ndarray'>
0


In [7]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [8]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [9]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(d)
print(type(d))
print(d.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
<class 'numpy.ndarray'>
3


In [10]:
#list vs array
a=[1,2,3,4]
b=[5,6,7,8]
print(a+b)#merges values and prints two lists in one list

[1, 2, 3, 4, 5, 6, 7, 8]


In [13]:
c=np.array([1,2,3,4])
d=np.array([5,6,7,8])
print(a+b)#adds values of both arrays in same postion of arrays

[ 6  8 10 12]


In [17]:
#sum
e=sum(a)
print(e)
print(np.sum(c+d))

10
208


In [19]:
#mean
print(np.mean(c+d))

13.0
